# Generated by Django 4.2.7 on 2025-07-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='company_email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.CreateModel(
            name='CalculateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_tax', models.IntegerField()),
                ('pay_after_tax', models.IntegerField()),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.quoterequest')),
            ],
        ),
    ]
