# Generated by Django 4.2.7 on 2025-07-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quoterequest_company_email_calculatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='avg_employee_pay',
            field=models.IntegerField(),
        ),
    ]
